name       : libburn
version    : 1.4.6
release    : 3
source     :
    - http://files.libburnia-project.org/releases/libburn-1.4.6.tar.gz : 9d36faab25478c01122a65873133b7fc60eb5ffbe12710d5757a7c3574227071
license    : GPL-2.0
component  : programming.library
summary    : libburn is a library by which preformatted data get onto optical media
description: |
    libburn is a library by which preformatted data get onto optical media: CD, DVD, BD (Blu-Ray). On Linux it uses either /dev/sgN (on kernel 2.4 with ide-scsi) or /dev/srM , /dev/hdX ( on kernel 2.6). On FreeBSD it uses /dev/cdN, eventually via atapicam. On Solaris addresses look like /dev/rdsk/cXtYd0s2.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
