name       : libburn
version    : 1.5.6
release    : 6
source     :
    - https://files.libburnia-project.org/releases/libburn-1.5.6.tar.gz : 7295491b4be5eeac5e7a3fb2067e236e2955ffdc6bbd45f546466edee321644b
homepage   : https://dev.lovelyhq.com/libburnia/web/wiki
license    : GPL-2.0-or-later
component  : programming.library
summary    : libburn is a library by which preformatted data get onto optical media
description: |
    libburn is a library by which preformatted data get onto optical media: CD, DVD, BD (Blu-Ray). On Linux it uses either /dev/sgN (on kernel 2.4 with ide-scsi) or /dev/srM , /dev/hdX ( on kernel 2.6). On FreeBSD it uses /dev/cdN, eventually via atapicam. On Solaris addresses look like /dev/rdsk/cXtYd0s2.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
